version: "3.9"
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=chat_app
    ports:
      - "5442:5432"
    volumes:
      - /var/lib/chat_app/data/ # persist data even if container shuts down
  redis:
    image: redis:7.0.4-alpine3.16
    ports:
      - '16379:6379'